# .github/workflows/deploy.yml
name: Deploy Lambda Function

on:
  push:
    branches:
      - main
# Add "id-token" with the intended permissions. 
permissions:
  contents: 'read'
  id-token: 'write'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
         # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment package
        run: zip -r function.zip node_modules index.mjs

      - name: Update Lambda function
        run: aws lambda update-function-code --function-name myLambdaFunction --zip-file fileb://function.zip
